FROM apache/airflow:2.9.3-python3.10

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends default-jre-headless procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    pyspark==3.5.1 \
    delta-spark==3.2.0 \
    clickhouse-connect==0.8.6 \
    kafka-python==2.0.2 \
    acryl-datahub==0.12.0

